const Database = require('better-sqlite3');
const db = new Database('database.db', { verbose: console.log });

// Nota: Estoy usando los nombres de las columnas que definimos en tu setup (descripcion, serie_modelo...)
const insertarItem = db.prepare(`
  INSERT INTO items (description, series_model, quantity, fixed_notes)
  VALUES (?, ?, ?, ?)
`);

// Lista completa extraída del INVENTARIO DE TRASLADO DE EQUIPOS DE SIMULACIÓN
const inventarioCompleto = [
    ['MEDICAL X NENASIM', 'SIN NS', 1, 'CAJA ABIERTA'],
    ['COMPUTADORA ALL IN ONE LENOVO', '304 42906153/MP2GSN2W', 1, 'CAJA ABIERTA'],
    ['MONITOR LENOVO THINKCENTRE 23.8 PULGADAS', 'ERSIDAL', 1, 'CAJA ABIERTA'],
    ['REALWEAR NAVIGATOR 520 LENTES INTELIGENTES', 'V30BMNF2', 4, 'CAJAS ABIERTAS'],
    ['ALHUA CINTROLADOR DE RECONOCIMIENTO FACIAL', 'GU', 1, 'ADAPTADORES CARGADOR REALWEAR USB 3.0'],
    ['ALHUA NETWORK CAMERA', '127111', 4, 'CABLE HDMI KRAMER'],
    ['M&B ELECTRONICS MONITOR DE DESFRIBILADOR', '97-0101010', 1, ''],
    ['RESPIFIX RESUCITADOR DESECHABLE (AMBU)', 'AA09E09PAG50073', 2, ''],
    ['TABLA RIGIDA PARA RCP', 'DM 7000/DM2308010', 3, 'ROJA'],
    ['TABLETA/COMPUTADORA DELL LATITUDE', 'THIA75721', 1, 'CAJA ABIERTA'],
    ['ESTUCHE DE DIAGNOSTICO WELCH ALLYN', 'SC-PAG', 2, 'SABANA DESECHABLE AZUL NAFARRETE PAQUETE CON 10'],
    ['ESPEJO VAGINAL DESECHABLE', 'N/A', 1, ''],
    ['INSTA 360 ACTION CAM', 'IAQEF2401VFDNM', 1, ''],
    ['INSTA360 SELFIE STICK TRÍPODE', 'X002R5D6T9', 1, ''],
    ['MSI TARJETA GRÁFICA MAG A850GL', '3067ZP8A23CE010421002931', 1, 'CAJA ABIERTA'],
    ['GAUMARD SUSIE $2400 ACCESORIOS', 'M 30081560', 1, 'Paquete de Accesorios Completo'],
    ['GAUMARD SUSIE 2400 CAJA EXTRA', '$5410070', 1, ''],
    ['GAUMARD SUSIE $2400 SIMULADOR', '$5410070', 1, ''],
    ['GAUMARD SUSIE 2400 CAJA 10/10 EXTRA', '5410070', 1, 'CAJA ABIERTA INCLUYE: MICROSOFT SURFACE PRO 9, FUNDA KENSIGTON, TECLADO, AUDIFONOS'],
    ['COMPUTADORA LAPTOP HP VICTUS', '5CD3209X5Z', 1, 'CAJA ABIERTA'],
    ['KYOTO KAGAKU SIMULADOR DE PACIENTE CARDIOLÓGICO CON BASE Y LLANTAS', '11389-900-A', 1, 'CAJA ABIERTA'],
    ['KYOTO KAGAKU MW10A SIMILADOR DE PACIENTE CARDIOLÓGICO CAJA EXTRA', '11389-900A-', 1, ''],
    ['KYOTO KAGAKU MW10A SIMILADOR DE PACIENTE CARDIOLÓGICO CAJA EXTRA CON ACCESORIOS', '11369-900-A', 1, 'CAJA ABIERTA INCLUYE: BOLSA, MANUALES, CABLES'],
    ['MOUSE Y TECLADO LOGITECH MK270 PARA KYOTO KAGAKU', '2424SY00MSH9', 1, 'CAJA ABIERTA'],
    ['HAL $5301 SIMILADOR DE PACIENTE ADULTO CAJA #4', '22410252', 1, ''],
    ['HAL $5301 SIMILADOR DE PACIENTE ADULTO CAJA #5', 'ERSIDAL 22410252', 1, ''],
    ['HAL S5301 SIMULADOR DE PACIENTE ADULTO CAIA EXTRA', '22410252', 1, ''],
    ['GAUMARD VICTORIA SIMULADOR DE NACIMIENTO AVANZADO (CAJA 1/8)', 'V2311491', 1, ''],
    ['GAUMARD VICTORIA SIMULADOR DE NACIMIENTO AVANZADO (CAJA 2/8)', 'V2311491', 1, ''],
    ['GAUMARD VICTORIA SIMULADOR DE NACIMIENTO AVANZADO (CAJA 3/8)', 'V2311491', 1, ''],
    ['GAUMARD VICTORIA SIMULADOR DE NACIMIENTO AVANZADO (CAJA 4/8)', 'V2311491', 1, ''],
    ['COMPUTADORA DELL ALL IN ONE PARA GAUMARD VICTORIA CAJA 5/8', 'V2311491', 1, ''],
    ['GAUMARD VICTORIA SIMULADOR DE NACIMIENTO AVANZADO (CAJA 6/8)', 'V2311491', 1, 'CAJA DE MISCELÁNEOS/ EXTRAS'],
    ['GAUMARD VICTORIA SIMULADOR DE NACIMIENTO AVANZADO (CAJA 7/8)', 'V2311491', 1, 'CAJA DE MISCELÁNEOS/ EXTRAS'],
    ['GAUMARD VICTORIA SIMULADOR DE NACIMIENTO AVANZADO (CAJA 8/8)', 'V2311491', 1, ''],
    ['ENTRENADOR DE AUSCULTACIÓN PULMONAR KYOTO KAGAKU LSAT CAJA 1/2', 'K24ME0001790', 1, ''],
    ['ENTRENADOR DE AUSCULTACIÓN PULMONAR KYOTO KAGAKU LSAT CAJA 2/2', 'K24ME0001790', 1, ''],
    ['ELEVATE PED 300 FULL BODY ARIA SIMULADOR MEDIUM SKIN TONE', 'NO. PEDIDO $14976', 1, 'CAJA ABIERTA'],
    ['TRUCORP MANIQUÍ RCP E INTUBACION CON ACCESORIOS', 'SIN NO. DE SERIE', 1, ''],
    ['TECLADO Y MOUSE LOGITECH PARA TRUCORP MANIQUÍ RCP', '2413SY03LMKO', 1, 'CAJA ABIERTA'],
    ['MONTURA DE PARED PARA TV SWIFTMOUNT', 'SIN. NO SERIE', 1, ''],
    ['GAUMARD TORSO DE ADULTO PARA RCPD PARA USO CON OMNI 2', 'CPR51706844', 1, ''],
    ['CAJA EXTRA PARA GAUMARD TORSO DE ADULTO PARA RCP D PARA USO CON OMNI 2', 'CPR51706844', 1, ''],
    ['GAUMARD PACIENTE AVANZADO DE ENFERMERÍA CON SEXOS INTERCAMBIABLES CAJA PEQUEÑA #5', '$5410070', 1, ''],
    ['GAUMARD $300.110.M2 CODE BLUE III NEWBORN WIRELESS SIMULATOR', 'F2409620W', 1, ''],
    ['GAUMARD 5300.110.M2 CODE BLUE III NEWBORN WIRELESS SIMULATOR CAJA DE EXTRAS', 'F2409620W', 1, 'CAJA ABIERTA INCLUYE: OMNI 2, FUNDA, MANUAL'],
    ['KYOTO KAGAKU EVALUADOR DE SIMULADOR DE SUTURA', 'K24ME0002169', 1, ''],
    ['MONITOR DE ESCRITORIO 27 PULGADAS IIYAMA-KYOTO KAGAKU', '7875420007', 1, ''],
    ['KYOTO KAGAKU SIMULADOR YAYE', '24092720', 1, ''],
    ['KYOTO KAGAKU ENTRENADORES DE PRACTICA DE SUTURA CAJA CON 2 PIEZAS', 'M83/11219-100', 1, ''],
    ['KYOTO KAGAKU ENTRENADORES DE PRACTICA DE SUTURA CAJA CON 1 PIEZA', 'M83/11219-100', 1, ''],
    ['ALMOHADA DE GEL', 'N/A', 4, ''],
    ['SIM X REALIDAD VIRTUAL META QUEST 3 GAFAS DE REALIDAD VIRTUAL', 'N/A', 1, 'CAJA ABIERTA CON 5 EQUIPOS'],
    ['CAJA DE RIELES/VARILLAS METÁLICAS', 'DEGI', 4, ''],
    ['TRIPIE METALICO PARA SOLUCIONES', 'N/A', 1, ''],
    ['LÁMPARA CON TRIPIE BLANCA', 'N/A', 1, '']
];

// Transacción para insertar todo rápidamente
const poblarBaseDeDatos = db.transaction((items) => {
    for (const item of items) {
        insertarItem.run(item[0], item[1], item[2], item[3]);
    }
});

poblarBaseDeDatos(inventarioCompleto);
console.log(`¡Éxito! Se insertaron ${inventarioCompleto.length} equipos en la base de datos.`);